routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->middleware('auth')->name('home');

Route::prefix('admin')
    ->as('admin.')
    ->middleware(['auth', 'account:admin'])
    ->group(function () {

        Route::get('/', [App\Http\Controllers\Admin\MainController::class, 'index'])->name('home');

        Route::resource('users', App\Http\Controllers\Admin\UserController::class)->only([
            'index', 'show', 'edit', 'update', 'destroy'
        ]);
        Route::resource('books', App\Http\Controllers\Admin\BookController::class)->only([
            'index', 'create', 'store', 'show', 'edit', 'update', 'destroy'
        ]);

});

Route::prefix('profile')
    ->as('profile.')
    ->middleware(['auth', 'account:user'])
    ->group(function () {

        Route::get('/', [App\Http\Controllers\Profile\ProfileController::class, 'index'])->name('home');

        Route::get('/search', [App\Http\Controllers\Profile\SearchController::class, 'index'])->name('search');

        Route::prefix('my')->as('user.')->group(function () {
            Route::get('/', [App\Http\Controllers\Profile\ProfileController::class, 'show'])->name('show');
            Route::get('/edit', [App\Http\Controllers\Profile\ProfileController::class, 'edit'])->name('edit');
            Route::post('/update', [App\Http\Controllers\Profile\ProfileController::class, 'update'])->name('update');
        });

        Route::prefix('books')->as('books.')->group(function () {
            Route::get('/', [App\Http\Controllers\Profile\BookController::class, 'index'])->name('index');
            Route::get('{book}', [App\Http\Controllers\Profile\BookController::class, 'show'])->name('show');
        });
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'books';

    protected $fillable = [
        'title',
        'description',
        'publishing_house',
        'year_publishing',
        'isbn',
        'image'
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function authors()
    {
        return $this->belongsToMany(Author::class);
    }

}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\BookStoreRequest;
use App\Http\Requests\Admin\BookUpdateRequest;
use App\Models\Author;
use App\Models\Book;
use App\Models\Category;
use App\Services\BookService;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function index()
    {
        $books = Book::get();
        return view('admin.books.index', ['books' => $books]);
    }

    public function create(Request $request)
    {
        $categories = Category::get();
        $authors = Author::get();
        return view('admin.books.create', ['categories' => $categories, 'authors' => $authors]);
    }

    public function store(BookStoreRequest $request)
    {
        $bookService = new BookService();
        $book = $bookService->create($request);

        return redirect()->route('admin.books.show', $book);
    }

    public function show(Book $book)
    {
        return view('admin.books.show', ['book' => $book]);
    }

    public function edit(Book $book)
    {
        $categories = Category::get();
        $authors = Author::get();
        return view('admin.books.edit', ['book' => $book, 'categories' => $categories, 'authors' => $authors]);
    }

    public function update(BookUpdateRequest $request, Book $book)
    {
        $bookService = new BookService();
        $bookService->update($request, $book);

        return redirect()->route('admin.books.show', $book);
    }

    public function destroy(Book $book)
    {
        $bookService = new BookService();
        $bookService->remove($book);

        return redirect()->route('admin.books.index');
    }
}

app/Http/Controllers/Profile/BookController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Models\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function index()
    {

    }

    public function show(Book $book)
    {
        return view('profile.book.show', ['book' => $book]);
    }
}

resources/views/admin/books/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        @include('admin.components.menu')


        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Книга</div>

                    <div class="card-body">

                        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.books.store') }}">
                            @csrf

                            <div class="row mb-3">
                                <label for="authors" class="col-md-4 col-form-label text-md-end">Автор</label>

                                <div class="col-md-6">
                                    <select name="authors[]" id="authors" class="form-control @error('authors') is-invalid @enderror" multiple required>
                                        @forelse ($authors as $author)
                                            <option value="{{ $author->id }}" >{{ $author->name }}</option>
                                        @empty
                                            <option selected disabled>Пусто</option>
                                        @endforelse
                                    </select>

                                    @error('authors')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="categories" class="col-md-4 col-form-label text-md-end">Категория</label>

                                <div class="col-md-6">
                                    <select name="categories[]" id="categories" class="form-control @error('categories') is-invalid @enderror" multiple required>
                                        @forelse ($categories as $category)
                                            <option value="{{ $category->id }}" >{{ $category->name }}</option>
                                        @empty
                                            <option selected disabled>Пусто</option>
                                        @endforelse
                                    </select>

                                    @error('categories')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Название</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('title') is-invalid @enderror" name="title" required>

                                    @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Описание</label>

                                <div class="col-md-6">
                                    <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" required></textarea>

                                    @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Издательство</label>

                                <div class="col-md-6">
                                    <input id="publishing_house" type="text" class="form-control @error('publishing_house') is-invalid @enderror" name="publishing_house" required>

                                    @error('publishing_house')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="year_publishing" class="col-md-4 col-form-label text-md-end">Год издания</label>

                                <div class="col-md-6">
                                    <input id="year_publishing" type="number"  class="form-control @error('year_publishing') is-invalid @enderror" name="year_publishing" required>

                                    @error('year_publishing')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="isbn" class="col-md-4 col-form-label text-md-end">ISBN</label>

                                <div class="col-md-6">
                                    <input id="isbn" type="text" class="form-control @error('isbn') is-invalid @enderror" name="isbn" required>
                                    @error('isbn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="row mb-3">
                                <label for="image" class="col-md-4 col-form-label text-md-end">Обложка</label>

                                <div class="col-md-6">
                                    <input id="image" type="file" class="form-control @error('image') is-invalid @enderror" name="image" required>

                                    @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Создать
                                    </button>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        @include('admin.components.menu')


        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Книга</div>

                    <div class="card-body">

                        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.books.update', $book) }}">
                            @csrf
                            @method('PUT')

                            <div class="row mb-3">
                                <label for="authors" class="col-md-4 col-form-label text-md-end">Автор</label>

                                <div class="col-md-6">
                                    <select name="authors[]" id="authors" class="form-control @error('authors') is-invalid @enderror" multiple required>
                                        @forelse ($authors as $author)
                                            <option value="{{ $author->id }}" {{ $book->authors->contains('id', $author->id) ? 'selected' : '' }}>{{ $author->name }}</option>
                                        @empty
                                            <option selected disabled>Пусто</option>
                                        @endforelse
                                    </select>

                                    @error('authors')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="categories" class="col-md-4 col-form-label text-md-end">Категория</label>

                                <div class="col-md-6">
                                    <select name="categories[]" id="categories" class="form-control @error('categories') is-invalid @enderror" multiple required>
                                        @forelse ($categories as $category)
                                            <option value="{{ $category->id }}" {{ $book->categories->contains('id', $category->id) ? 'selected' : '' }}>{{ $category->name }}</option>
                                        @empty
                                            <option selected disabled>Пусто</option>
                                        @endforelse
                                    </select>

                                    @error('categories')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Название</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('title') is-invalid @enderror" value="{{ $book->title }}" name="title" required>

                                    @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Описание</label>

                                <div class="col-md-6">
                                    <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description">{{ $book->description }}</textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">Издательство</label>

                                <div class="col-md-6">
                                    <input id="publishing_house" type="text" class="form-control @error('publishing_house') is-invalid @enderror" value="{{ $book->publishing_house }}" name="publishing_house" required>

                                    @error('publishing_house')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="year_publishing" class="col-md-4 col-form-label text-md-end">Год издания</label>

                                <div class="col-md-6">
                                    <input id="year_publishing" type="number"  class="form-control @error('year_publishing') is-invalid @enderror" value="{{ $book->year_publishing }}" name="year_publishing" required>

                                    @error('year_publishing')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="isbn" class="col-md-4 col-form-label text-md-end">ISBN</label>

                                <div class="col-md-6">
                                    <input id="isbn" type="text" class="form-control @error('isbn') is-invalid @enderror" value="{{ $book->isbn }}" name="isbn" required>
                                    @error('isbn')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="row mb-3">
                                <label for="image" class="col-md-4 col-form-label text-md-end">Обложка</label>

                                <div class="col-md-6">
                                    <img src="/storage/{{ $book->image }}" width="200px" height="200px" alt="">
                                    <br>
                                    <input id="image" type="file" class="form-control @error('image') is-invalid @enderror" name="image">

                                    @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Изменить
                                    </button>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/books/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        @include('admin.components.menu')


        <a href="{{ route('admin.books.create') }}" class="btn btn-success mb-3">Создать</a>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#id</th>
                    <th scope="col">Название</th>
                    <th scope="col">Издательство</th>
                    <th scope="col">Год издания</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Действия</th>
                </tr>
            </thead>
            <tbody>
                @forelse($books as $book)
                    <tr>
                        <th scope="row">{{ $book->id }}</th>
                        <td>{{ $book->title }}</td>
                        <td>{{ $book->publishing_house }}</td>
                        <td>{{ $book->year_publishing }}</td>
                        <td>{{ $book->isbn }}</td>
                        <td>
                            <a href="{{ route('admin.books.show', $book->id) }}" class="btn btn-success">Просмотр</a>
                            <a href="{{ route('admin.books.edit', $book->id) }}" class="btn btn-primary">Редактирование</a>
                            <form action="{{ route('admin.books.destroy', $book->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Удалить</button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <p>Пусто</p>
                @endforelse
            </tbody>
        </table>

    </div>

@endsection

resources/views/admin/books/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        @include('admin.components.menu')


        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Книга</div>

                    <div class="card-body">

                        <div class="row mb-3">
                            <label for="categories" class="col-md-4 col-form-label text-md-end">Автор</label>

                            <div class="col-md-6">
                                <select class="form-control" disabled multiple>
                                    @forelse ($book->authors as $author)
                                        <option value="{{ $author->id }}" >{{ $author->name }}</option>
                                    @empty
                                        <option selected disabled>Пусто</option>
                                    @endforelse
                                </select>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="categories" class="col-md-4 col-form-label text-md-end">Категория</label>

                            <div class="col-md-6">
                                <select class="form-control" disabled multiple>
                                    @forelse ($book->categories as $category)
                                        <option value="{{ $category->id }}" >{{ $category->name }}</option>
                                    @empty
                                        <option selected disabled>Пусто</option>
                                    @endforelse
                                </select>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Название</label>

                            <div class="col-md-6">
                                <input id="name" type="text" disabled class="form-control" name="title" value="{{ $book->title }}" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Описание</label>

                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" disabled name="description" required>{{ $book->description }}</textarea>
                            </div>

                        </div>
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Издательство</label>

                            <div class="col-md-6">
                                <input id="publishing_house" type="text" class="form-control" disabled value="{{ $book->publishing_house }}" name="publishing_house" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="year_publishing" class="col-md-4 col-form-label text-md-end">Год издания</label>

                            <div class="col-md-6">
                                <input id="year_publishing" type="number"  class="form-control" disabled value="{{ $book->year_publishing }}" name="year_publishing" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="isbn" class="col-md-4 col-form-label text-md-end">ISBN</label>

                            <div class="col-md-6">
                                <input id="isbn" type="text" class="form-control" disabled value="{{ $book->isbn }}" name="isbn" required>
                            </div>

                        </div>
                        <div class="row mb-3">
                            <label for="image" class="col-md-4 col-form-label text-md-end">Обложка</label>

                            <div class="col-md-6">
                                <img src="/storage/{{ $book->image }}" width="200px" height="200px" alt="">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection